const Terms = () => {
    return (
        <>
            <section className="bg-[#f7f7f7] py-20">
                <div className="bs-container">
                    <div className="row max-sm:px-5">
                        <div className="col-12">
                            <h1 className="text-[#444762] poppins-600 text-[30px] xs:text-[40px] lg:text-[60px]">Terms of use</h1>
                            <p className="text-[black] mt-2 opacity-60 poppins-500  xs:text-[18px] sm:text-[20px]">UPDATED 2021 - 2022</p>
                        </div>
                    </div>
                </div>
            </section>
            <section className="bg-[white]">
                <div className="bs-container">
                    <div className="row mt-10">
                        <div className="col-12">
                            <div className="lg:pl-10 max-sm:px-5">
                                <p className="policy-text">
                                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                                </p>
                                <p className="policy-text mt-8">
                                    This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Platform (as defined herein).
                                </p>
                                <p className="policy-text-bold mt-8">Introduction</p>
                                <div className="pl-7">
                                    <ol className="list-decimal mt-8">
                                        <li className="policy-text ">
                                            <p >The Platform (hereinafter defined) refer to an internet based app/application owned and operated by Ryzer wealth corp Private Limited, a company incorporated under the laws of India (CIN: U68100AP2023PTC111341) and having its registered office located at 9-24, Venkatagiri colony, Morampudi, Rajahmundry, Andhra Pradesh, Pincode: 533107. Ryzer wealth corp private limited is registered as a real estate broker with the Real Estate Regulatory Authority, Karnataka. The term “RYZER” on the Platform may refer to one or more entities that are part of the Ryzer wealth corp private limited.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>Accordingly, the terms Ryzer wealth corp private limited, website, “we”, “our” and “us” in these Terms of Use may either refer to one or more entities, on a joint or several basis (as the context may require) that form part of the Ryzer wealth corp private limited. Ryzer wealth corp private limited and its Platform “RYZER” enables its users to access real estate assets including commercial, retail, open plots, Farm lands, warehousing, hotels etc.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>These terms and conditions of use (“<span className="poppins-700">Terms of Use</span>”) describe the terms applicable to your use of the Ryzer wealth corp private limited website (www.ryzer.app), mobile-optimized versions of the website, digital applications, and any other media formats for the purposes of use and promotion of Ryzer wealth corp private limited (collectively referred to as the “<span className="poppins-700">Platform</span>”), and other products, software and services, which may be offered from time to time, on the Platform or offline, owned or licensed and operated by Ryzer wealth corp private limited and its affiliates, such as email, chat, bulletin board services, information related to recommendations, news groups, forums, communities, personal web pages, calendars, and/or other message (together the “<span className="poppins-700">Services</span>”).</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p className="uppercase">NOTHING CONTAINED ON THE PLATFORMS SHOULD BE CONSTRUED AS AN AUTHORIZATION BY THE SECURITIES AND EXCHANGE BOARD OF INDIA (“<span className="poppins-700">SEBI</span>”) TO SOLICIT INVESTMENTS NOR SHOULD THE PLATFORMS BE CONSTRUED AS A SEBI AUTHORIZED CROWDFUNDING PLATFORM OR A STOCK EXCHANGE, OR THEIR EQUIVALENT. THE PLATFORMS ARE USED BY US TO PROVIDE SERVICES TO OUR REGISTERED USERS, AND WE DO NOT SEEK TO SOLICIT INVESTMENTS FROM THE PUBLIC AT LARGE.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>By accessing the Platform, registering as a User with the Platform, submitting any material to the Platform, or using any of the Services, you expressly agree to accept these Terms of Use in full. Accordingly, if you disagree with these Terms of Use or any part of these Terms of Use, you may not access or otherwise use the Platform or Services.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Definitions</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>Unless the context otherwise requires, for the purpose of these Terms of Use, the following terms shall have the meaning ascribed to them hereunder:</p>
                                            <ol className="list-decimal mt-10 pl-10">
                                                <li className="policy-text">
                                                    <p>“<span className="poppins-700">Applicable Law</span>” means all laws, ordinance, statutes, rules, orders, decrees, injunctions, licences, permits, approvals, authorizations, consents, waivers, privileges, agreements and regulations of any governmental authority/court of law having jurisdiction over the relevant matter including any interpretations thereof, in effect;</p>
                                                </li>
                                                <li className="policy-text mt-5">
                                                    <p >“<span className="poppins-700">Intellectual Property Rights</span>”  means all patents, designs and drawings, trademarks, service marks, logos, domain names and utility models, copyrights, inventions, brand names and business names and any similar rights and the benefit (subject to the burden) of any of the foregoing (in each case whether registered or otherwise, and includes applications for the grant of any of the foregoing and the right to apply for any of the foregoing in any part of the world);</p>
                                                </li>
                                            </ol>
                                        </li>
                                    </ol>
                                    <ul className="list-disc mt-10">
                                        <li className="policy-text-bold">
                                            <p className="policy-text">
                                                “<span className="poppins-700">Terms and Conditions</span>” means these Terms of Use, Privacy Policy, Transaction Documents (if any) or any other document which outlines or governs the relationship between the User and Ryzer wealth corp private limited regarding the use and access of Platform and Services;
                                            </p>
                                        </li>
                                    </ul>
                                    <ol className="list-decimal mt-8">
                                        <li className="policy-text">
                                            <p>“<span className="poppins-700">Transaction Documents</span>” means the various documents required to be executed by a User that governs its relationship with Ryzer wealth corp private limited;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>“<span className="poppins-700">User</span>” means you, and does not include your permitted assigns, successors, trustees, successors-in-interest, heirs and legal representatives and the like, unless the context requires otherwise;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>“<span className="poppins-700">User Account</span>” means the personal online account created by User to access and use the Platform;</p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-5">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text"><p className="poppins-700">Access</p>
                                                    <p className="mt-2">Subject to the compliance with Terms of Use and payment of fees (if and as applicable), Ryzer wealth corp private limited grants you a non-transferable, non-exclusive, license to use the Platform for your personal, non-commercial use.</p>
                                                </li>
                                            </ol>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-10">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Intellectual Property Rights</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>You acknowledge that all the Intellectual Property Rights in the Platform are owned either by Ryzer wealth corp private limited or Ryzer wealth corp private limited’s licensors, or by the content suppliers, as the case may be, but in no event by the User except as explicitly provided herein. The use, access and provision of the Platform does not transfer to you or any third party any rights, title or interest in or to such Intellectual Property Rights. Ryzer wealth corp private limited or Ryzer wealth corp private limited’s licensors, or content suppliers reserve all Intellectual Property Rights not specifically grated in these Terms of Use.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>Subject to the restrictions under Paragraph 5 (Restrictions on Use) below, you agree that all copyright and other proprietary notices on any Platforms content must be retained on all copies thereof.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Restrictions on Use</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>The rights granted to you under these Terms of Use are subject to the restrictions provided below.</p>
                                        </li>
                                        <li className="policy-text  mt-5">
                                            <p>You shall not:</p>
                                            <ol className="mt-7 pl-7 list-decimal">
                                                <li className="policy-text">
                                                    <p>license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Platform, without express written consent of Ryzer wealth corp private limited;</p>
                                                </li>
                                                <li className="policy-text mt-3">
                                                    <p>access the Platform in order to build a similar or competitive service;</p>
                                                </li>
                                            </ol>
                                        </li>
                                    </ol>
                                    <ul className="list-disc mt-7">
                                        <li className="policy-text-bold">
                                            <p className="policy-text">
                                                copy, reproduce, distribute, republish, download, displayed, poste or transmit in any form or by any means, any part of the Platforms, for any commercial purpose or otherwise, without express written consent of Ryzer wealth corp private limited;
                                            </p>
                                        </li>
                                    </ul>
                                    <ol className="list-decimal mt-5">
                                        <li className="policy-text">
                                            <p>use the Platform in any way that causes, or may cause, damage to the Platform, its Users  or impair the availability or accessibility of the Platform or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>abuse, harass, impersonate, intimidate or threaten other Users;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>post or transmit, or cause to be posted or transmitted, any content that is harmful, infringing, libellous, defamatory, abusive, offensive, obscene, pornographic, paedophilic, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or otherwise violates any Applicable Law or right of any third party; or that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nations;</p>
                                        </li>
                                    </ol>
                                    <ul className="list-disc mt-7">
                                        <li className="policy-text-bold">
                                            <p className="policy-text">
                                                use the Platform for any unauthorized purpose, or in violation of any Applicable Law or these Terms of Use;
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, access to another User’s account, or private information from any User;
                                            </p>
                                        </li>
                                    </ul>
                                    <ol className="list-decimal mt-5">
                                        <li className="policy-text">
                                            <p>create or send unwanted email (spam) to any other User;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>infringe upon the Intellectual Property Rights of Ryzer wealth corp private limited, other Users, or any third party, while accessing or using the Platform;</p>
                                        </li>
                                    </ol>
                                    <ul className="list-disc mt-7">
                                        <li className="policy-text-bold">
                                            <p className="policy-text">
                                                submit comments linking to affiliate programs, multi-level marketing schemes, sites repurposing existing stories or off-topic content;
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                post, email, transmit, upload, or otherwise make available any material that contains software viruses or any other computer code, trojan horse or other code with malicious, disruptive and/or destructive features, files or programs designed or functioning to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment, including the Platform;
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                use any robot, spider, scraper, sniping software or other automated means to access the Platform for any purpose;
                                            </p>
                                        </li>
                                    </ul>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text">
                                            <p>conduct any systematic or automated data collection activities on or in relation to the Platform without express written consent of Ryzer wealth corp private limited;</p>
                                        </li>
                                    </ol>
                                    <ul className="list-disc mt-7">
                                        <li className="policy-text-bold">
                                            <p className="policy-text">
                                                use the Platform or any part of it to transmit or send unsolicited commercial communications, or for any other purposes related to marketing, without express written consent of Ryzer wealth corp private limited;
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                take any action that imposes, or may impose, in our sole discretion, an unreasonable or disproportionately large load/strain on our infrastructure;
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                sell or otherwise transfer your User Account/ profile, or allow any third party to use or access your User Account; or
                                            </p>
                                        </li>
                                        <li className="policy-text-bold mt-3">
                                            <p className="policy-text">
                                                without our prior written consent, reverse engineer, frame, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software obtained from or part of the Platform.
                                            </p>
                                        </li>
                                    </ul>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">User Accounts</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>You may need to register an account with us in order to use or access the Platform or the Services.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>To be eligible to register an account with us, you must be of such age that you can enter into legally binding agreements as per Applicable Laws where You reside in.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>By registering an account with us (“<span className="poppins-700">Registered User</span>”), you represent and warrant that you are such age that you can enter into legally binding agreements as per Applicable Laws where You reside in, that all information you submit is true, accurate and complete and you shall comply with these Terms of Use. You further represent and warrant that: (a) all required registration information you submit is truthful, accurate and complete; (b) you will maintain the accuracy of such information; and (c) You are eligible to enter into legally binding agreements under the Applicable Laws where You reside in. You acknowledge that Your use of the Platform shall be deemed to be genuine and any action taken by Ryzer wealth corp private limited or any third party based on the same shall be deemed to be valid. You represent and warrant that you are an individual of legal age or a HUF or a company or a trust or an LLP eligible to form a binding contract as per the Applicable Laws of your domicile (or if not, you’ve received your parent’s or guardian’s or governing body’s permission to use the Platform and such approving authority has agreed to these Terms of Use on your behalf).</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>You will be solely responsible for maintaining the confidentiality of your User Account and log-in details, and we will not be responsible for misuse of your User Account by any third party, whether authorized by you or not. You may never use another User’s account without permission of such User and us. You also prohibited from sharing your log-in details or allowing anyone access to your account or do anything that might put your User Account or other User Accounts at risk.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>You are responsible for any activity on the Platform arising out of any failure to keep your User Account confidential and may be held liable for any losses arising out of such a failure. You agree to notify us immediately of any unauthorized use of your User Account or any other breach of security.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>Ryzer wealth corp private limited reserves the right to refuse to offer access to or use of the Platform to any person or entity at Ryzer wealth corp private limited’s sole discretion including by changing its eligibility criteria at any time.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>The Platform may allow a User to create more than one profile under it, especially in case of family members, relatives and affiliates. In the event that Your profile has been created under another User’s profile, it will be deemed that you have accorded your consent to such User to create such profile. Any action initiated under Your profile shall be deemed to have been done with your consent and due authorization. You may at any time place a request to delink your profile linked to a User by writing an email to operations@ryzer.app. All such delinking requests will be processed at the earliest and a new User profile will be created for you.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Mobile Apps and Third-Party Services</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>When you access and use the Platform, you may also be using the services of one or more of our affiliates or third-party service providers, including wireless carrier, mobile platform provider, or application store (e.g. GooglePlay, Apple iPhone Store, Windows Store etc.). The use of these services by you shall be subject to specific documentation signed with such parties with separate policies, terms of use, privacy policy, and fees of these affiliates or third parties (including fees for downloading and using mobile applications, and any operator network and roaming charges), and you hereby explicitly agree to comply with same.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>You may have to use third-party payment gateway to make payments to us, or to other vendors through the Platform. The processing of payments will be subject to the terms, conditions and privacy policies of the payment processor, in addition to these Terms of Use, and you hereby explicitly agree to comply with same. The terms of your payment will be based on your payment method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your payment method. We are not responsible for any error by the payment processor. </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">External Content</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>The Platform might contain links to third party websites, services, and advertisements for third parties. Third party websites may in turn link to the Platform. You acknowledge and agree that third party websites, advertisements and services are not under the control of Ryzer wealth corp private limited and that Ryzer wealth corp private limited is not responsible for the information, content, products, services, advertising, or other materials which may be provided therein (“<span className="poppins-700">External Content</span>”).</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Additionally, we may furnish reports, summaries, charts, data, valuation reports, and analysis prepared by third parties for you to provide better understanding of the opportunity and the risks associated with you (“<span className='poppins-700'>Third Party Materials</span>”). You understand and acknowledge that your reliance on any Third Party Materials is at your own risk, and you should always obtain independent business, legal and tax advice in relation to all your decisions.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                The inclusion of any link to such External Content or Third Party Materials on the Platform does not imply Ryzer wealth corp private limited’s endorsement, sponsorship, or recommendation of such External Content or Third Party Material. Ryzer wealth corp private limited specifically states that the links to External Content and Third Party Materials have been provided for convenience purpose and Ryzer wealth corp private limited does not review, approve, monitor, warrant, make any representations, or assume any liability whatsoever in connection with the use or reliance of such External Content.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                We strongly advise you to read the terms and conditions and privacy policies of any third party websites or services that you click on, access or use.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Privacy Policy</p>

                                                </li>

                                            </ol>
                                            <p className="mt-3">Please review our Privacy Policy to understand what kind of information we gather from you and the specific measures we take to protect your personal information. The Privacy Policy is hereby incorporated into these Terms of Use by reference.</p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Use of Cookies and Analytical Tools</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>We use data collection devices such as “cookies” on certain pages of the Platform to manage our users’ sessions, store preferences, serve ads, track information, help analyze our web page flow, measure promotional effectiveness, and promote trust and safety.</p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                The types of information cookies collect may include personal information such as your name, your IP address, contact details, personal preferences, and details of your use of the Platform.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                You have the ability to either accept or decline the use of cookies on your computer / device, whether you are registered with us or not. Typically, you can configure your browser to not accept cookies. However, declining the use of cookies may limit your access to certain features of the Platform.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                In order to avail Services from us, we may share your personal information to third parties and/or regulatory bodies, subject to Applicable Law. We may also allow third-party advertising companies and marketing services companies to serve ads and other content when you visit the Platform and elsewhere on the internet and in other media. These third-party service providers may place third-party cookies and use the information about your visits, buying behaviour, browsing history, preferences, to this Platform and elsewhere to serve ads and other content to you. We cannot control or access cookies used by third-party service providers.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                In addition, we may provide your personal information to marketing services companies on an anonymous and aggregate basis to allow them to market their products or services, or for other marketing purposes. This may be information we received from you offline and online.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Limitations, Disclaimers and Exclusions of Liability</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                All information, content, materials, products (including software) and Services included on or otherwise made available to you on or through the Platform are provided on an “as is” without any implied or express representations or warranties, and other terms which might otherwise be implied by statute, common law or the law of equity including, but not limited to, implied warranties of merchantability, suitability and fitness for a particular purpose.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Ryzer wealth corp private limited does not warrant that the information, content, materials, products (including software) or other Services included on or otherwise made available to you on or through the Platform (whether by Ryzer wealth corp private limited, its affiliates, suppliers, content providers and advertisers), Ryzer wealth corp private limited’s servers or electronic communications sent by Ryzer wealth corp private limited are free of viruses or other harmful components.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Ryzer wealth corp private limited shall not be liable for any damages whatsoever, including but without limitation to any direct, indirect, special, consequential, punitive or incidental damages, or damages for business losses, loss of contracts or business relationships, profits, data, database, software or other intangibles, damage to goodwill or reputation, or the cost of procurement of substitute goods and services, arising out of or related to the use, inability to use, performance or failure of the Platform and any materials posted thereon, products (including software) or other Services or otherwise made available to you on or through the Platform, irrespective of whether such damages were foreseeable or arise in contract, tort, equity, restitution, by statute, at common law or otherwise.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Without prejudice to the generality of the foregoing paragraph, Ryzer wealth corp private limited does not warrant or represent:
                                            </p>
                                            <ol className="list-decimal pl-7 mt-2">
                                                <li className="policy-text">
                                                    <p>
                                                        the completeness or accuracy of the information published on the Platform;
                                                    </p>
                                                </li>
                                                <li className="policy-text">
                                                    <p>
                                                        that the material on the Platform is up to date;
                                                    </p>
                                                </li>
                                                <li className="policy-text">
                                                    <p>
                                                        that the Platform or any Service on the Platform will remain available.
                                                    </p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                You understand and acknowledge that an investment in real estate assets is speculative in nature and involves a high degree of risk, including the risk of loss of capital. An investment in real estate asset is suitable only for sophisticated investors who fully understand and are capable of bearing the risks of an investment in real estate assets. An investor should only invest in real estate assets as part of an overall investment strategy, and only if the investor is able to withstand a total loss of its investment. No guarantee or representation is made by us that you will achieve your investment objectives or will receive a return of your capital.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                You accept that we have an interest in limiting the personal liability of our officers and employees to the extent permitted by law and, having regard to that interest, you agree that you will not bring any claim personally against our officers or employees in respect of any losses you suffer in connection with the Platform or these Terms of Use.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                You accept that we have an interest in limiting the personal liability of our officers and employees to the extent permitted by law and, having regard to that interest, you agree that you will not bring any claim personally against our officers or employees in respect of any losses you suffer in connection with the Platform or these Terms of Use.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                The laws of certain jurisdictions do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and you might have additional rights.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                We make no representation or warranty regarding the Platform:
                                            </p>
                                            <ol className="list-decimal pl-7 mt-2">
                                                <li className="policy-text">
                                                    <p>
                                                        meeting your requirements,
                                                    </p>
                                                </li>
                                                <li className="policy-text">
                                                    <p>
                                                        being accurate or reliable;
                                                    </p>
                                                </li>
                                                <li className="policy-text">
                                                    <p>
                                                        being accessible in an uninterrupted, timely, secure or error-free manner.
                                                    </p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Access to and use of the Platform by you is contingent on your internet connection and we shall not be held liable for any loss that occurs due to breaks in your internet accessibility.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                In the event that the Platform or any portion thereof is not accessible due to technical problems or for any other reason, Users are not entitled to claim any loss or damage from us, and we are not obligated to compensate any such User.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                If you are dissatisfied or harmed by the Platforms or anything related to it, your sole remedy shall be to terminate these Terms of Use by closing your account on the Platform.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Breach of Terms of Use</p>
                                                </li>
                                            </ol>
                                            <p className="mt-3">
                                                Without prejudice to Ryzer wealth corp private limited’s other rights under these Terms of Use, if you breach these Terms of Use in any way, or if we reasonably suspect that you have breached these Terms And Conditions in any way, we may take such action as we deem appropriate to deal with the breach, including (a) temporarily suspend your access to the Platform, (b) permanently prohibit you from accessing the Platform, (c) blocking computers / devices using your IP address from accessing the Platform, (d) contacting any or all of your internet service providers and request that they block your access to the Platform, (e) commence legal action against you, whether for breach of contract or otherwise; and/or (f) suspend or delete your User Account.
                                            </p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Termination</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Either you or Ryzer wealth corp private limited may terminate the relationship between us relating to the usage of the Platform, with or without cause, at any time to be effective immediately. Please note that such termination shall only govern Your usage of the Platform and any Services offered to You by an affiliate of Ryzer wealth corp private limited or a third party shall continue to be governed by the terms agreed in such individual service agreements.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                While Ryzer wealth corp private limited will try to provide you prior notice of any termination of your account, you agree that Ryzer wealth corp private limited may under certain circumstances, immediately terminate your User Account. Causes for termination may include, but shall not be limited to, your breach of the Terms and Conditions, requests by law enforcement or government agencies, non-payment of fees owed by you in connection with the access and use of the Platform or the Services.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Ryzer wealth corp private limited shall not be liable to you or any third party for the termination or suspension of any Platform. If you object to any Terms and Conditions, your only recourse is to: (a) discontinue use of the Platform or the Services; and (b) notify Ryzer wealth corp private limited of such discontinuance.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                Upon termination of the relationship, your right to access or use the Platform and the Services shall immediately cease. You shall have no right, and Ryzer wealth corp private limited shall have no obligation thereafter, to execute any of your uncompleted tasks or forward any unread or unsent messages to you or any third party. Once your User Registration is terminated, cancelled or suspended, any data that you have stored on the Platform may not be retrieved later.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Governing Law and Dispute Resolution</p>
                                                </li>
                                            </ol>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                These terms and conditions shall be governed by and construed in accordance with the laws of India.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                The determination of existence of any disputes, the nature of the disputes and how it should be handled relating to these terms and conditions shall be decided by Ryzer wealth corp private limited. Subject to the above, the courts of Bengaluru City will have exclusive jurisdiction over issues arising out of these terms and conditions.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Entire Agreement</p>
                                                </li>
                                            </ol>
                                            <p className="mt-3">
                                                These Terms of Use, together with the Privacy Policy constitute the entire agreement between you and Ryzer wealth corp private limited in relation to your use of the Platform and supersede all previous agreements in respect of your use of the Platform. Please note, however, that other aspects of your use of Services may be governed by additional agreements. If any term of this Terms of Use expressly conflicts with any term of any individual service agreement executed with an affiliate of Ryzer wealth corp private limited or a third party, such conflict will be resolved at our sole discretion.
                                            </p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Changes to the Terms of Use and Privacy Policy</p>
                                                </li>
                                            </ol>
                                            <p className="mt-3">
                                                Ryzer wealth corp private limited reserves the right, at its sole discretion, to change, modify, add or remove any portion of the Terms of Use or the Privacy Policy, in whole or in part, at any time. If we make any substantial changes to these Terms of Use or the Privacy Policy, we may notify you by posting notice of the changes on the Platform. In such cases, changes will be effective upon expiry of seven (7) calendar days following our posting of notice of the changes on the Platform. However, these changes will be effective immediately for new users of our Platform. In the event a User has any reservation or objections to any change in the Terms of Use or the Privacy Policy, such User may exercise its right to terminate this relationship under Clause 15. Your continued use of the Platform and/or the Services made available on or through the Platform after any changes to the Terms of Use or the Privacy Policy are posted will be considered acceptance of such changes.
                                            </p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Confidentiality</p>
                                                </li>
                                            </ol>
                                            <p className="mt-3">
                                                Subject to the express permissions of these Terms of Use, you and we will protect each other’s Confidential Information from unauthorized use, access or disclosure in the same manner as each protects its own Confidential Information, but with no less than reasonable care. Except as otherwise expressly permitted pursuant to these Terms of Use, each of us may use each other’s Confidential Information solely to exercise our respective rights and perform our respective obligations under these Terms of Use. The term ‘Confidential Information’ shall mean all information disclosed or accessed by you to us or by us to you which is labelled “confidential” (or with a similar legend) or which a reasonable person would understand to be confidential given the nature of the information and circumstances of disclosure. Notwithstanding the foregoing, Confidential Information shall not include information that (a) was already known to the receiving party at the time of disclosure by the disclosing party; (b) was or is obtained by the receiving party by a third party not known by the receiving party to be under an obligation of confidentiality with respect to such information; (c) is or becomes generally available to the public other than by violation of these Terms of Use; or (d) was or is independently developed by the receiving party without use of the disclosing party’s Confidential Information.
                                            </p>
                                        </li>
                                    </ol>
                                    <ol className="list-decimal mt-7">
                                        <li className="policy-text">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Communication</p>
                                                </li>
                                            </ol>

                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                If you need to give Ryzer wealth corp private limited a notice of anything, including infringement of your rights, or any other non-compliance with these Terms of Use, or you have any questions on these Terms of Use, please write to Mr. Hashim Qadeer Khan at legal@eallyy.app.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <p>
                                                If we need to give you notice of anything, we shall write to you at the email address you provide to us.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-5">
                                            <ol className="list-decimal pl-10">
                                                <li className="policy-text">
                                                    <p className="poppins-700">Disclaimer</p>
                                                </li>
                                            </ol>

                                        </li>
                                    </ol>
                                    <ul className="mt-5">
                                        <li className="policy-text">
                                            <p>Under no circumstances is the information mentioned herein to be construed as an offer to sell or a solicitation of an offer to buy any securities, or as an offer to provide any services.</p>
                                        </li>
                                        <li className="policy-text mt-7">
                                            <p>
                                                This information mentioned herein has not been approved by any supervisory or regulatory authority.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-7">
                                            <p>
                                                Nothing contained herein may be relied upon as a guarantee, promise, assurance, or a representation as to the future. No assurance can be given that the objective or strategy or vision or mission regarding the services offered by us will be achieved. The User is cautioned not to put undue reliance on any of the assumptions, scenarios, projections, representative data, expected yields or other information contained herein.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-7">
                                            <p>
                                                The User should also note that there can be no assurance that any of the prospective opportunities described in this document will be consummated or any other arrangement with any other person will fructify, or in either case continue even if consummated or fructified.
                                            </p>
                                        </li>
                                        <li className="policy-text mt-7">
                                            <p>
                                                Past performance is not indicative of future results and there can be no assurance that the arrangement described herein will achieve its goals. Certain information contained herein constitutes “forward looking statements” which can be identified by the use of forward-looking terminology such as “may”, “will”, “us”, “should”, “expect”, “anticipate”, “target”, “project”, “estimate”, “intend” or “continue”, “believe” or the negatives thereof, or other variations thereon. Because of various risks and uncertainties, actual events or results or actual performance may differ materially from the events, results or performance reflected or contemplated in such forward-looking statements. As a result, the User should not rely on such forward-looking statements.
                                            </p>
                                        </li>
                                    </ul>
                                    <ul className="mt-7 list-disc">
                                        <li className="policy-text-bold">
                                            <p>
                                                Waiver of Rights
                                            </p>
                                        </li>
                                    </ul>
                                    <ul className="mt-5">
                                        <li className="policy-text">
                                            <p>
                                                Ryzer cealth corp private limited’s failure to enforce any provision of this Terms of Use shall not be deemed to be a waiver of such provision nor of the right to enforce such provisions.
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default Terms
